package qlhtt.Enum;

public enum LuaChonNhanVien {
    TRANGTONGQUAT,
    BANHANG,
    DANHSACHHOADON,
    CAPNHATTHONGTINKHACHHANG,
    CAPNHATTHONGTINNHACUNGCAP,
    QUANLYSANPHAM,
    NHAPHANG,
    DANHSACHPHIEUNHAP,
    THONGKEDOANHTHU,
    THONGKEHOADON,
    THONGKEPHIEUNHAP,
    CAPNHATTHONGTINNGUOIDUNG,
    DOI_MAT_KHAU,
    DANG_XUAT

}
