package qlhtt.Enum;

public enum LuaChonNguoiQuanLy {
    TRANGTONGQUAT,
    THEMNHANVIEN,
    CAPNHATTRANGTHAIHOATDONG_NHANVIEN,
    TAOCHIETKHAU,
    CAPNHATTRANGTHAICHIETKHAU,
    THONGKESANPHAM,
    THONGKEDOANHTHU,
    THONGKEHOADON,
    THONGKEPHIEUNHAP,
    CAPNHATTHONGTINNGUOIDUNG,
    DOI_MAT_KHAU,
    DANG_XUAT
}
